name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Neodevils
          numOfAssignee: 1
